### ISSUE TITLE
link from citation to caption for HTML/PDF, custom PDF caption

### ISSUE THREAD

**Issue by bbest** [adletaw/captioner#20]
Hi @adletaw,

Did you see my pull request a month ago https://github.com/adletaw/captioner/pull/17 "link from citation to caption for HTML/PDF, custom PDF caption"?

Here's what I said...

Thanks so much for this great package! I've added a little `link` argument to the captioner function to customize HTML and PDF outputs for linking from citation to caption. The intended output type is determined with `fmt = knitr::opts_knit$get()[['rmarkdown.pandoc.to']]`.

I was originally motivated to write this because of wanting a single manuscript to output as HTML (for web), PDF (for final) and DOC (for track changes with coauthors). But outputting to PDF generates "Figure 1: Figure 1-1" or similar since labeling gets handled internally. So now the prefix and number get stripped in the caption for PDF, ie deferring to internal LaTex handling.

This might also help with #13, #6.

From the vignette addendum...

### Linking to Figures / Tables

You may want to link from the citation to the caption for easy reference. For HTML, an HTML anchor `<a name="id"}></a>` is placed before the caption and markdown style internal link `[](#id)` used for the citation.

```{r link_html}
fig <- captioner(link = TRUE)
fig("sausage", "Never saw such links!")
fig("sausage", display = "cite")
```
```
## [1] "<a name=\"Figure_1\"}></a>Figure  1: Never saw such links!"
## [1] "[Figure  1](#Figure_1)"
```

For PDF, a [Latex cross-referencing](https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing#Introduction) technique of `\label{id}` and `\ref{id}` are used. 

```{r link_pdf}
fig <- captioner(link = TRUE, fmt = 'latex')
fig("sausage", "Never saw such links!")
fig("sausage", display = "cite")
```
```
## [1] "Never saw such links!\\label{Figure_1}"
## [1] "Figure  \\ref{Figure_1}" 
```

Since for PDF output figure numbering is internally handled, display of special numbering otherwise defined in the `level` argument is ignored in the citation and caption output PDF. This further handles the duplication of caption labels, such as "Figure 1: Figure 1:" that you would otherwise see when not using the `link = TRUE` option and pdf output.

The output type will be detected from using `rmarkdown::render()`, whether by command or using the Knit dropdown menu when editing an Rmarkdown document in the RStudio IDE (see [rmarkdown.rstudio.com](http://rmarkdown.rstudio.com/). The argument  `fmt` used above is not documented in the captioner function, but used here in the vignette simply to show the different renderings of the intermediary markdown document before being passed along to [pandoc](http://pandoc.org).

**Comment by adletaw** [comment]
Hello @bbest!

In fact, I *did* see your pull request, but thank you for copying the content of it here.  I am glad you are enjoying using the package.

The issue here is that I need to sit down and think about how many things I think should be added to `captioner`, and what those things should be.  Right now, it is a fairly stable and simple set of functions that solve a small problem.  I am disinclined to get into the realm of typesetting and streamlining workflow, since that isn't `captioner`'s job.  To be honest, however, I just haven't thought it all out carefully yet.  Unfortunately, I wont really be able to do that until I finish some other very large projects that I am working on.  Sadly, it may be several months before I really get a chance to think out the next phase for `captioner`.

On the upside, I am quite happy that you were able to fork `captioner` and modify it to achieve your own ends.  It is fantastic that you are taking advantage of the positive attributes of open source software.  While `captioner` is in stasis, I will be sure to direct anyone looking for a `link` feature to your fork.

**Comment by adletaw** [comment]
*captioner* is no longer being developed.  Check out [bookdown](https://github.com/rstudio/bookdown) for captioning with markdown.
